allowBuilds:
  baileys: false
  msgpackr-extract: false
  protobufjs: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8
minimumReleaseAgeExclude:
  - whatsappd@0.4.0-alpha.3
  - "@oxlint/plugins@1.79.0"
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
